spring:
  profiles:
    active:
      - prod
      - cat
      - EN

mm:
  username: YmlSuperuser
  password: YmlDbPassword
  jdbcurl: YmlSomeUrlforDB

---

spring:
  config:
    activate:
      on-profile: prod

mm:
  username: YmlProdSuperuser
  password: YmlProdDbPassword
  jdbcurl: YmlProdSomeUrlforDB
